version: '3'
services:
  postgres:
    image: postgres:11.12-alpine
    restart: always
    environment:
      POSTGRES_DB: 'rarus'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - .:/var/lib/postgresql/data
  rarus.app:
    image: rarus.app:latest
    container_name: rarus.app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      POSTGRES_DB: 'rarus'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      LISTEN_PORT: 3003
    restart: always
    links:
      - postgres
    ports:
      - 3003:3003
