version: '3'
services:
  postgres:
    image: postgres:11.12-alpine
    restart: always
    environment:
      POSTGRES_DB: 'rarus'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    volumes:
      - ../dump.sql:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
  rarus.app:
    image: rarus.app:latest
    container_name: rarus.app
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
    restart: always
    links:
      - mysqldb
    ports:
      - 3000:3000
